logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    de.jsmal.core.ServletEngine: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

security:
  expiry: 36000 # minutes for valid certificate

#Just for INFO
structure:
  version: 0.4.2

de:
  jsmal:
    cruddao:
      version: 0.2.0

servlet:
  app:
    version: 0.1.4

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    dbhost: ${dbhost:localhost}
    dbport: ${dbport:3306}
    url: jdbc:mysql://${spring.datasource.dbhost}:${spring.datasource.dbport}/db_proto?useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false&useLegacyDatetimeCode=false
    username: ${usernameDB:admuser}
    password: ${passwordDB:ThePassword}
#Server port for embedded Tomcat in JAR
server:
  port: 8090


