logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    de.jsmal.core.engine.search: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

security:
  expiry: 36000 # minutes for valid certificate

#Just for INFO
structure:
  version: 0.3.8

de:
  jsmal:
    cruddao:
      version: 0.1.9

servlet:
  app:
    version: 0.1.4

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/db_proto?useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false&useLegacyDatetimeCode=false
    username: admuser
    password: ThePassword
#Server port for embedded Tomcat in JAR
server:
  port: 8090


